from typing import Dict


proximity_map: Dict["str", "str"] = {
    "q": "qwasedzx",
    "w": "wqesadrfcx",
    "e": "ewrsfdqazxcvgt",
    "r": "retdgfwsxcvgt",
    "t": "tryfhgedcvbnju",
    "y": "ytugjhrfvbnji",
    "u": "uyihkjtgbnmlo",
    "i": "iuojlkyhnmlp",
    "o": "oipklujm",
    "p": "plo['ik",
    "a": "aqszwxwdce",
    "s": "swxadrfv",
    "d": "decsfaqgbv",
    "f": "fdgrvwsxyhn",
    "g": "gtbfhedcyjn",
    "h": "hyngjfrvkim",
    "j": "jhknugtblom",
    "k": "kjlinyhn",
    "l": "lokmpujn",
    "z": "zaxsvde",
    "x": "xzcsdbvfrewq",
    "c": "cxvdfzswergb",
    "v": "vcfbgxdertyn",
    "b": "bvnghcftyun",
    "n": "nbmhjvgtuik",
    "m": "mnkjloik",
    " ": " ",
    "1": "11qw2",
    "2": "2w3e",
    "3": "32we4r",
    "4": "43er5t",
    "5": "54rt6",
    "6": "65ty7",
    "7": "76yu8",
    "8": "87ui9",
    "9": "98uio0",
    "0": "09iop-",
    "[OVERRIDE]": "!@#$%^&*()_+|}?><.~",
}
